# Generated by Django 2.1.5 on 2022-05-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thereviewguides', '0005_useranswer_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='username',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
